name: Deploy

on: [repository_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - run: |
          git clone https://github.com/openmls/openmls
          cd openmls/book
          mdbook build 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && github.event.action == 'deploy'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./openmls/book/book
